[tool.poetry]
name = "dvc-demo"
version = "0.1.0"
description = ""
authors = ["Wiznikvibe <nikhilshetty439@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dvc = "^3.59.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
