channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.3.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
